### ISSUE TITLE
在移除了一些package以后项目似乎正常运行,这些package是否有安装的必要?

### ISSUE THREAD

**Issue by InsHomePgup** [daidaibg/IofTV-Screen#28]
移除的package....
    // "async-validator": "^4.2.5",
    // "follow-redirects": "^1.15.2",
    // "glob-parent": "^6.0.2",
    // "node-forge": "^1.3.1",
    // "ejs": "^3.1.8",
    // "uglify-js": "^3.17.4"

**Comment by daidaibg** [comment]
你感觉可以去就去呗，我这个是从一个项目迁移出来的。

**Comment by InsHomePgup** [comment]
对...主要是我不太清楚依赖关系,我现在要把这个大屏合并到另外一个项目里去要安装相关依赖来着,简单看了下依赖就是这部分似乎没用到....你这个版本比面条那个版本缩放丝滑哈哈哈
