### ISSUE TITLE
node 16 18 都不行

### ISSUE THREAD

**Issue by xuehu96** [daidaibg/IofTV-Screen#40]
16的时候
error commander@12.1.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"

18的时候
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.20.4"

 😭

**Comment by daidaibg** [comment]
要14版本
